### ISSUE TITLE
evaluation.py

### ISSUE THREAD

**Issue by weigq** [bearpaw/pytorch-pose#10]
hi,
i ran the training   code and met the following errror:
```
Traceback (most recent call last):
  File "example/mpii.py", line 318, in <module>
    main(parser.parse_args())
  File "example/mpii.py", line 104, in main
    valid_loss, valid_acc, predictions = validate(val_loader, model, criterion, args.debug, args.flip)
  File "example/mpii.py", line 233, in validate
    acc = accuracy(score_map.cuda(), target, idx)
  File "~/pytorch-pose/pose/utils/evaluation.py", line 61, in accuracy
    acc[i+1] = dist_acc(dists[:, idxs[i]-1, :])
IndexError: index 10 is out of range for dimension 1 (of size 6)
```
is this a bug?

**Comment by weigq** [comment]
i have found the reason, this is due to the version of pytorch.

**Comment by weigq** [comment]
in detail, 
https://github.com/bearpaw/pytorch-pose/blob/6f1966e70eb75f8c3f15943f770c7a5780e2373b/pose/utils/evaluation.py#L18
```
maxval, idx = torch.max(scores.view(scores.size(0), scores.size(1), -1), 2)
```
in version 0.1.12, torch.max here returns BatchSize * 16 *1
while in version0.2 torch.max here returns BatchSize * 16

**Comment by bearpaw** [comment]
@weigq Thanks very much! Would you please create a pull request to fix this problem?

**Comment by weigq** [comment]
@bearpaw , i have PR.

btw, how many epochs did you set in training your pre-trained model, i tried the training code, but get bad loss and acc on validation set. could you provide a log file of your training, if it is convenient (the log.txt in your pre-trained model is empyt)
thx

**Comment by bearpaw** [comment]
@weigq  Thanks.

I found the original log file has been overwritten. You may try to evaluate on val set and use the evaluation code to get the "real" PCKh value. See if the results match.

**Comment by weigq** [comment]
@bearpaw 
i have run the eva_PCKh  and got right value. 
however, when i continue training your pre-trained model, in the first epoch (in fact is epoch 37), i get bad  acc on val set:
```
==> creating model 'hg4'
=> loading checkpoint 'checkpoint/mpii/hg4/model_best.pth.tar'
=> loaded checkpoint 'checkpoint/mpii/hg4/model_best.pth.tar' (epoch 37)
    Total params size: 25.03M
    Mean: 0.4404, 0.4440, 0.4327
    Std:  0.2458, 0.2410, 0.2468

Epoch: 37 | lr: 0.00005000
the length of train_loader: 3708
Processing |>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>| (3708/3708) Data: 0.000147s | Batch: 0.965s | Total: 1:05:17 | ETA: 0:00:02 | Loss: 0.0014
length of output:493
Processing |>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>| (493/493) Batch: 0.385s | Total: 0:03:09 | ETA: 0:00:01 | Loss: 0.0023 | Acc:  0.013273152
```

**Comment by bearpaw** [comment]
It seems quite strange. Maybe there are some bugs (and the final accuracy is lower than the original torch code https://github.com/anewell/pose-hg-train)
