### ISSUE TITLE
关于MPII训练精度问题

### ISSUE THREAD

**Issue by liuchanfeng165** [bearpaw/pytorch-pose#105]
你好，请问你是用科学计算卡还是GTX系列训练呢？我用两块GTX1070，但s2结果MPII log显示比你的log差8个百分比，你有这方面经验吗，可否指点原因？
my log as follow：
23.000000	0.000250	0.000348	0.000347	0.667625	0.698335	
24.000000	0.000250	0.000347	0.000313	0.671120	0.694273	
25.000000	0.000250	0.000344	0.000464	0.673781	0.697057
u log as follow：
23.000000	0.000500	0.000844	0.000814	0.753865	0.766151	
24.000000	0.000500	0.000842	0.000810	0.755048	0.767318	
25.000000	0.000500	0.000837	0.000807	0.760711	0.768832
batch_size = 64 ,lr=2.5-4
是学习率影响的？

**Comment by liuchanfeng165** [comment]
I got it by some related issues~

**Comment by TPLeung** [comment]
@liuchanfeng165 How can you fix the problem? Can you share some training recipes with us? Thx~

**Comment by liuchanfeng165** [comment]
> @liuchanfeng165 How can you fix the problem? Can you share some training recipes with us? Thx~

According the final mAP not  only acc.
