### ISSUE TITLE
coco_annotations_2014.json

### ISSUE THREAD

**Issue by sdustdk1427** [bearpaw/pytorch-pose#114]
Why does the link to these files show that the page does not exist?Such as mpii_annotations.json, coco_annotations_2014.json and coco_annotations_2017.json.Can someone share it with me?

**Comment by bearpaw** [comment]
You can generate the json files by running the scripts in the `miscs` folder. Also see https://github.com/bearpaw/pytorch-pose/issues/121#issuecomment-765604111
