### ISSUE TITLE
“scale” message 

### ISSUE THREAD

**Issue by xiaoxin05** [bearpaw/pytorch-pose#118]
hi，I want to train my custom datasets，but i don‘t know your annntation about  “scale” ？can you share me？ Thank  you！
@bearpaw bearpaw

**Comment by bearpaw** [comment]
`scale` denote person scale w.r.t. 200 px height, http://human-pose.mpi-inf.mpg.de/#download

**Comment by xiaoxin05** [comment]
ok，thank you for reply. it means i need people height in my custom datasets，divided to 200
