### ISSUE TITLE
test error!

### ISSUE THREAD

**Issue by zilesazoyi2** [bearpaw/pytorch-pose#12]
Thanks for you code! could you give me some advice? thanks a lot!
sun@sunwin:~$ cd /home/sun/pytorch-pose
sun@sunwin:~/pytorch-pose$ CUDA_VISIBLE_DEVICES=0 python example/mpii.py -a hg --stacks 2 --blocks 1 --checkpoint checkpoint/mpii/hg_s2_b1 --resume checkpoint/mpii/hg_s2_b1/model_best.pth.tar -e -d
usage: mpii.py [-h] [--arch ARCH] [-j N] [--epochs N] [--start-epoch N]
               [--train-batch N] [--test-batch N] [--lr LR] [--momentum M]
               [--weight-decay W] [--print-freq N] [-c PATH] [--resume PATH]
               [-e] [-d] [-f]
mpii.py: error: argument --arch/-a: invalid choice: 'hg' (choose from 'hg1', 'hg2', 'hg4', 'hg8', 'preresnet110', 'preresnet1202', 'preresnet20', 'preresnet32', 'preresnet44', 'preresnet56')

**Comment by bearpaw** [comment]
This might be caused by the outdated code. Please use `git pull` to get the latest code. I updated the code recently.

**Comment by bearpaw** [comment]
This issue is closed for no further discussion.
