### ISSUE TITLE
Hello, I encountered the following problems when I was training the code. What is the reason? Python: 2.7, Pytorch: 0.4.1

### ISSUE THREAD

**Issue by Nanawu123** [bearpaw/pytorch-pose#120]
Hello, I encountered the following problems when I was training the code. What is the reason?
Python: 2.7, Pytorch: 0.4.1
![捕获](https://user-images.githubusercontent.com/73815521/103479329-f6f63400-4e07-11eb-9769-254950f259e5.PNG)

**Comment by bearpaw** [comment]
Please refer to https://github.com/bearpaw/pytorch-pose/issues/121#issuecomment-765604111
