### ISSUE TITLE
`RuntimeError` in `HourglassNet` because of possibly incorrect `scale_factor` for `F.interpolate`

### ISSUE THREAD

**Issue by joshuacwnewton** [bearpaw/pytorch-pose#124]
## Error

I am trying to export [`HourglassNet`](https://github.com/bearpaw/pytorch-pose/blob/7ce6642f777e9da6249bd5b05330d57fa09ea37a/pose/models/hourglass.py#L96) to `.onnx` using [`torch.onnx.export`](https://pytorch.org/docs/stable/onnx.html). I am getting the following error:

 ```python
  File "", line, in _hour_glass_forward
    out = up1 + up2
  RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 3
```

## Cause

I think the cause of the error is due to the `scale_factor` used for [`F.interpolate`](https://pytorch.org/docs/stable/generated/torch.nn.functional.interpolate.html#torch.nn.functional.interpolate). (Additional context: 7ce6642f777e9da6249bd5b05330d57fa09ea37a):

https://github.com/bearpaw/pytorch-pose/blob/7ce6642f777e9da6249bd5b05330d57fa09ea37a/pose/models/hourglass.py#L88-L89

* For the  `n > 1` case, `scale_factor=2` works well, and the dimensions for `up1` and `up2` match. For example:

    ![Screenshot from 2021-09-14 10-58-30](https://user-images.githubusercontent.com/16181459/133282005-8c5364a7-a83f-4e32-a714-8d09b62e2f29.png)

    ![Screenshot from 2021-09-14 10-58-58](https://user-images.githubusercontent.com/16181459/133282107-5dc38224-3c3d-4273-927e-94364ebaac5e.png)

* However, for the `n = 1` case, `scale_factor=2` causes a mismatch between the dimensions of `up1` (3) and `up2` (2):

    ![Screenshot from 2021-09-14 10-55-07](https://user-images.githubusercontent.com/16181459/133281391-9a835d9c-c56a-4374-8d9b-668bf8e68217.png)

    Hence the error reported above.

## Potential Solution

When I make the following changes:

```diff
        if n > 1:
            low2 = self._hour_glass_forward(n-1, low1)
+           scale_factor = 2
        else:
            low2 = self.hg[n-1][3](low1)
+           scale_factor = 3
        low3 = self.hg[n-1][2](low2)
-       up2 = F.interpolate(low3, scale_factor=2)
+       up2 = F.interpolate(low3, scale_factor=scale_factor)
        out = up1 + up2
```

The dimensions now match for all cases, and I no longer get the `RuntimeError`:

![Screenshot from 2021-09-14 11-08-59](https://user-images.githubusercontent.com/16181459/133283840-3645e17b-a462-43a4-9527-4eb9b943149a.png)

Disclaimer: I am not sure if this is an appropriate fix. If someone else could verify, please let me know.

**Comment by joshuacwnewton** [comment]
> ## Potential Solution
> 
> When I make the following changes:
> 
> ```diff
>         if n > 1:
>             low2 = self._hour_glass_forward(n-1, low1)
> +           scale_factor = 2
>         else:
>             low2 = self.hg[n-1][3](low1)
> +           scale_factor = 3
>         low3 = self.hg[n-1][2](low2)
> -       up2 = F.interpolate(low3, scale_factor=2)
> +       up2 = F.interpolate(low3, scale_factor=scale_factor)
>         out = up1 + up2
> ```
> 
> The dimensions now match for all cases, and I no longer get the `RuntimeError`:
> 
> ![Screenshot from 2021-09-14 11-08-59](https://user-images.githubusercontent.com/16181459/133283840-3645e17b-a462-43a4-9527-4eb9b943149a.png)
> 
> Disclaimer: I am not sure if this is an appropriate fix. If someone else could verify, please let me know.

Please disregard this fix. I was incorrect -- this does not work as intended when training the model. 

I will continue investigating why there is a discrepancy between ONNX exporting and training, but I will close this for now.

**Comment by bearpaw** [comment]
Thanks for looking into this and welcome to push this again once you found a solution.
