### ISSUE TITLE
Why does BN comes before Conv in BottleNeck layers?

### ISSUE THREAD

**Issue by sssruhan1** [bearpaw/pytorch-pose#14]
I was wondering, is there any special reasons why BN comes before Conv in pose/models/hourglass.py Bottleneck class?

**Comment by bearpaw** [comment]
This is exactly the same with the original code: https://github.com/anewell/pose-hg-train/blob/master/src/models/layers/Residual.lua

Actually, there are two versions of ResNet. The first one is the [CVPR 16 paper](https://arxiv.org/abs/1512.03385). In this version, BN and ReLU are placed after the Conv. In their later paper in [ECCV 16](https://arxiv.org/abs/1603.05027), they proposed an updated version of ResNet, where BN and ReLU are placed before Conv, called pre-activated ResNet. This can achieve the "pure" shortcut branch without any other "blocking" operation (like ReLU in the original ResNet). You may find the code in [Facebook's ResNet repo](https://github.com/facebook/fb.resnet.torch): 
* ResNet: https://github.com/facebook/fb.resnet.torch/blob/master/models/resnet.lua
* PreResNet: https://github.com/facebook/fb.resnet.torch/blob/master/models/preresnet.lua

**Comment by sssruhan1** [comment]
Thanks for the information!
