### ISSUE TITLE
One extra residual module?

### ISSUE THREAD

**Issue by bloodymeli** [bearpaw/pytorch-pose#17]
Hi,

I was wondering if there is an extra residual model in your model compared to the original implementation. In your code, the output of the hourglass is followed by: 
```
y = self.hg[i](x)
y = self.res[i](y)
y = self.fc[i](y)
score = self.score[i](y)
```

However, in the original implementation there is a sequence of 3  1X1 convolutions (the first two are followed by batch_norm and relu). 
```
-- First hourglass
local hg1 = hourglass(4,256,512,r6)

local l1 = lin(512,512,hg1)
local l2 = lin(512,256,l1)

-- First predicted heatmaps
local out1 = nnlib.SpatialConvolution(256,outputDim[1][1],1,1,1,1,0,0)(l2)
```

Can you please comment on that?

**Comment by bearpaw** [comment]
Hi @bloodymeli . This implementation is following the original code: https://github.com/anewell/pose-hg-train/blob/master/src/models/hg.lua#L52-L55

They use residuals (specifically, one residual) after each hourglass.
