### ISSUE TITLE
About rotation of the data augmentation

### ISSUE THREAD

**Issue by taokong** [bearpaw/pytorch-pose#23]
Hi, @bearpaw , very clear code!

In /pose/datasets/mpii.py line 95
`r = torch.randn(1).mul_(rf).clamp(-2*rf, 2*rf)[0] if random.random() <= 0.6 else 0`
The rotation angles are between [-60, 60]. It is not consistent with the Hourglass work and your paper(Multi-Context Attention for Human Pose Estimation) [-30, 30]. I also see similar codes at  [pose-attention](https://github.com/bearpaw/pose-attention/blob/master/train/data.lua) . 

Does larger angle variation help training of pose detection?

**Comment by bearpaw** [comment]
Sorry that I don't quite remember the reason for this setting. Maybe it's a mistake or maybe it is following a history version of pose-hg-train.

I believe the performances of different settings should be very similar. You can have a try.

**Comment by taokong** [comment]
Thanks
