### ISSUE TITLE
About your MPII data preprocessing code

### ISSUE THREAD

**Issue by zhiqiangdon** [bearpaw/pytorch-pose#25]
Hi, @bearpaw 

I read and ran your script https://github.com/bearpaw/pytorch-pose/blob/master/miscs/gen_mpii.m.
I find the sizes of training and validation sets in the generated json file are 22246 and 2958. However, the script https://github.com/shihenw/convolutional-pose-machines-release/blob/master/training/genJSON.m creates a json file containing 25925 training and 2958 validation samples. I find the difference of the training set is due to your code

`loc = find(sum(~bsxfun(@minus, tompson_i_p, [i;p]))==2, 1);
 loc2 = find(tompson.RELEASE_img_index == i);
if(~isempty(loc))
      validationCount = validationCount + 1;
      isValidation = 1;
 elseif (isempty(loc2))
      trainCount = trainCount + 1;
      isValidation = 0;
 else
      continue;
 end`

In file https://github.com/shihenw/convolutional-pose-machines-release/blob/master/training/genJSON.m, the corresponding code is
`loc = find(sum(~bsxfun(@minus, tompson_i_p, [i;p]))==2, 1);
if(~isempty(loc))
      validationCount = validationCount + 1;
      %fprintf('Tomspon''s validation! %d\n', validationCount);
      isValidation = 1
else
      isValidation = 0;
end`

The difference means that if there is one person an image belonging to the validation, you don't use all other persons on that image for the training, which results in fewer training samples at last. Do you have any specific reason of doing this? I think larger training set should be more beneficial. Are your results posted here https://github.com/bearpaw/pytorch-pose/ based on the smaller training set of size 22246?

Thanks!

**Comment by bearpaw** [comment]
I simply use 22246 here to match the settings in https://github.com/anewell/pose-hg-train
