### ISSUE TITLE
Are there bugs in gen_lsp.m?

### ISSUE THREAD

**Issue by djangogo** [bearpaw/pytorch-pose#26]
Hi @bearpaw 
Very great work!
In the file gen_lsp.m, 
https://github.com/bearpaw/pytorch-pose/blob/master/miscs/gen_lsp.m#L37-L48
https://github.com/bearpaw/pytorch-pose/blob/master/miscs/gen_lsp.m#L54-L60
```
oriTrTe.joints(7, 1:2, :) = mean(oriTrTe.joints(3:4,1:2,:));
oriTrTe.joints(8, 1:2, :) = mean(oriTrTe.joints(13:14,1:2,:));
```

I find that the coordinates of the thorax and the pelvis are calculated by the locations of shoulders and hips. 
If there are wrong locations of shoulders or hips, it will produce wrong calculated locations of thorax or pelvis
The calculation can be improved by add  condition  statement to judge whether the locations of shoulders and hips are right.

**Comment by bearpaw** [comment]
It's not exactly a bug. I think it's just acceptable. Actually, LSP is with some noise labels  (not mention the LSP ext dataset). 

If you're interested, you could use `v` to control the visibility of this joint. I'm also curious whether it is important or not.
