### ISSUE TITLE
bugs here

### ISSUE THREAD

**Issue by bertjiazheng** [bearpaw/pytorch-pose#27]
https://github.com/bearpaw/pytorch-pose/blob/b8dc3b3ef4af3dbfde0bfcf51cc900df2af7317a/pose/utils/transforms.py#L18

It seems a bug in color_normalization 

`
        t.sub_(m).div_(s)
`

**Comment by bearpaw** [comment]
Hi @bertjiazheng . It seems that original hourglass network didn't subtract mean.

I follow the implementation of convolutional pose machine to get slightly better result: https://github.com/shihenw/convolutional-pose-machines-release/blob/afda94fe0d53eb77c5fe948e607f199791f4073c/testing/src/applyModel.m#L94

You may also try to divide the std and see whether it helps improve the performance. Feedbacks are always welcome!

**Comment by wangziren1** [comment]
Hi @bearpaw, why don't you use original hourglass network that didn't subtract mean? I also see your hg-8
 training log and find your accuracy increase slowly than original paper. Does this result from nomalization i.e.image subtracting mean?

**Comment by bearpaw** [comment]
@wangziren1 Please try so if you are interested and give us a feedback. Thanks very much!
