### ISSUE TITLE
some explanations for the files

### ISSUE THREAD

**Issue by sssruhan1** [bearpaw/pytorch-pose#3]
Hi , 

I was wondering how did you generate some of the data files in evaluations folder? I feel like I can sort of guess what's inside these files, but it would be great if you could tell us how they are generated and what actually has been done.

For example:
data/mpii/mpii_annotations.json
evaluation/data/detections_out_format.mat
evaluation/data/detections.mat

Thanks in advance!

**Comment by bearpaw** [comment]
Hi, as stated in the readme, the mat files in the `evaluation/data` are adopted from http://www.cims.nyu.edu/~tompson/data/mpii_valid_pred.zip

The `data/mpii/mpii_annotations.json` is generated by using this code: https://github.com/shihenw/convolutional-pose-machines-release/blob/master/training/genJSON.m
(Maybe there are some modifications when generating my version of JSON file. I will upload my script later. Please stay in tuned!)

**Comment by sssruhan1** [comment]
Oh, I see. Thank you!

**Comment by Ivamcoder** [comment]
Hi @bearpaw ,
sorry for asking , I confused with dataset
I have a question in regard with mpii,
in your code the validation data and test data are same about 3000
Is it true for this dataset the evaluation and validation are same?
or for final evaluation needs to submit to a server?
