### ISSUE TITLE
what's the meaning of 'scale' in mpii dataset?

### ISSUE THREAD

**Issue by EthanGuan** [bearpaw/pytorch-pose#31]
if I use my own dataset, every image is 640 * 480, what's the value of scale should I set it to?

**Comment by bearpaw** [comment]
The scale keeps the height of the person as about 200 px. You should set the scale according to the groundtruth annotation or the detection bounding boxes.

**Comment by CoinCheung** [comment]
Hi, thanks for explaining!! 

If I did not misunderstand your answer above. I should compute the bounding box height with `h=200 x scale`, and with the center coordinates `(c0, c1)`, I could compute the `y` coordinate of the upper left point with: `y1=c1-h/2`. Is this the correct story? 

If I am not wrong about the heigt, what about the bounding box width? Shall I treat the bounding box as some rectangle box?

**Comment by YinZ-510** [comment]
@CoinCheung 
Hi, I also want to train this network on on my own dataset, my input picuture size is 720x1280，
but I don't know how to set the scale and center.
Can you give me some advice?

**Comment by DonaldKam** [comment]
@bearpaw The scale keeps the height of the person as about 200 px. You should set the scale according to the groundtruth annotation or the detection bounding boxes.
-----------------Well I guss it does not have to be height, but also can be weight. Actually, it should be max(h,w), Make sense?

**Comment by xiaoxin05** [comment]
@CoinCheung  Have you solved this problem? About scale and center？
