### ISSUE TITLE
bug in pose/datasets/mpii.py

### ISSUE THREAD

**Issue by linghai06** [bearpaw/pytorch-pose#34]
![image](https://user-images.githubusercontent.com/7567001/34507383-62c49382-f070-11e7-9c3f-f9bcbff83287.png)
I think the line

> if tpts[i, 0] > 0:

should be 

> if tpts[i, 1] > 0:

because when you do fliplr, x=0 is set to be x=width then there will be a "ground truth point" in upper right corner. Above is a compromised correction. Hopefully we are not doing flipud.

**Comment by bearpaw** [comment]
Thanks for pointing this out. I'll fix this in the next commit.
