### ISSUE TITLE
got stuck in training.

### ISSUE THREAD

**Issue by dongzhuoyao** [bearpaw/pytorch-pose#37]
```
Epoch: 54 | LR: 0.00005000
Processing |################################| (3708/3708) Data: 0.000265s | Batch: 0.286s | Total: 0:20:19 | ETA: 0:00:01 | Loss: 0.0033 | Acc:  0.7968
Processing |################################| (493/493) Data: 0.000184s | Batch: 0.127s | Total: 0:01:02 | ETA: 0:00:01 | Loss: 0.0035 | Acc:  0.8025

Epoch: 55 | LR: 0.00005000
Processing |################################| (3708/3708) Data: 0.000226s | Batch: 0.283s | Total: 0:20:22 | ETA: 0:00:01 | Loss: 0.0033 | Acc:  0.7994
Processing |################################| (493/493) Data: 0.000168s | Batch: 0.128s | Total: 0:01:02 | ETA: 0:00:01 | Loss: 0.0036 | Acc:  0.7947

Epoch: 56 | LR: 0.00005000
Processing |################################| (3708/3708) Data: 0.000174s | Batch: 0.249s | Total: 0:20:24 | ETA: 0:00:01 | Loss: 0.0033 | Acc:  0.7997
Processing |################################| (493/493) Data: 0.000158s | Batch: 0.128s | Total: 0:01:03 | ETA: 0:00:01 | Loss: 0.0038 | Acc:  0.8001

Epoch: 57 | LR: 0.00005000
Processing |################################| (3708/3708) Data: 0.000286s | Batch: 0.309s | Total: 0:20:31 | ETA: 0:00:01 | Loss: 0.0033 | Acc:  0.8026
Processing |################################| (493/493) Data: 0.000217s | Batch: 0.128s | Total: 0:01:03 | ETA: 0:00:01 | Loss: 0.0035 | Acc:  0.7993

Epoch: 58 | LR: 0.00005000
Processing |################################| (3708/3708) Data: 0.000279s | Batch: 0.296s | Total: 0:20:16 | ETA: 0:00:01 | Loss: 0.0033 | Acc:  0.8038
Processing |################################| (493/493) Data: 0.000223s | Batch: 0.122s | Total: 0:01:00 | ETA: 0:00:01 | Loss: 0.0036 | Acc:  0.7977

Epoch: 59 | LR: 0.00005000
Processing |######                          | (789/3708) Data: 0.000346s | Batch: 0.328s | Total: 0:04:18 | ETA: 0:15:57 | Loss: 0.0033 | Acc:  0.8042
```

it just stay here, and don't move any more.

**Comment by wangzheallen** [comment]
I also stuck when using 1 GPU, and when using two GPUs, I get  "RuntimeError: CUDNN_STATUS_MAPPING_ERROR" within 6 epoch

**Comment by bearpaw** [comment]
It sounds weird. Does this problem occur repeatedly?

**Comment by bearpaw** [comment]
@dongzhuoyao do you still have the problem as in https://github.com/bearpaw/pytorch-pose/issues/33 ?

**Comment by dongzhuoyao** [comment]
@bearpaw i tune the learning rate to 5e-5, the loss goes normal now, however, it got stuck as above saying.  

here is the traceback log may help you when I stop the process by ctl-c.

```
^CProcess Process-468:
Traceback (most recent call last):
Process Process-465:
Process Process-466:
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/home/hutao/.virtualenvs/pytorchgo/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 36, in _worker_loop
r = index_queue.get()
File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
self._target(*self._args, **self._kwargs)
File "/home/hutao/.virtualenvs/pytorchgo/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 36, in _worker_loop
File "/home/hutao/.virtualenvs/pytorchgo/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 36, in _worker_loop
r = index_queue.get()
File "/usr/lib/python2.7/multiprocessing/queues.py", line 374, in get
r = index_queue.get()
File "/usr/lib/python2.7/multiprocessing/queues.py", line 374, in get
racquire()
racquire()
KeyboardInterrupt
KeyboardInterrupt
return recv()
File "/home/hutao/.virtualenvs/pytorchgo/local/lib/python2.7/site-packages/torch/multiprocessing/queue.py", line 21, in recv
buf = self.recv_bytes()
KeyboardInterrupt
```

**Comment by bearpaw** [comment]
Hi @dongzhuoyao 
Would you please try to upgrade the PyTorch or even the python (by anaconda) and see if everything's going well?

**Comment by djangogo** [comment]
Hi @dongzhuoyao, @bearpaw 
I encountered this problem too.

`Processing |################################| (3708/3708) Data: 0.000495s | Batch: 0.349s | Total: 0:22:53 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8438
Processing |################################| (493/493) Data: 0.000101s | Batch: 0.149s | Total: 0:01:13 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8348

Epoch: 48 | LR: 0.00025000
Processing |################################| (3708/3708) Data: 0.000392s | Batch: 0.351s | Total: 0:22:48 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8440
Processing |################################| (493/493) Data: 0.000092s | Batch: 0.149s | Total: 0:01:13 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8362

Epoch: 49 | LR: 0.00025000
Processing |################################| (3708/3708) Data: 0.000135s | Batch: 0.327s | Total: 0:22:47 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8463
Processing |################################| (493/493) Data: 0.000098s | Batch: 0.148s | Total: 0:01:12 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8350

Epoch: 50 | LR: 0.00025000
Processing |################################| (3708/3708) Data: 0.000272s | Batch: 0.352s | Total: 0:22:50 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8466
Processing |################################| (493/493) Data: 0.000096s | Batch: 0.148s | Total: 0:01:13 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8412

Epoch: 51 | LR: 0.00025000
Processing |################################| (3708/3708) Data: 0.000735s | Batch: 0.490s | Total: 0:26:44 | ETA: 0:00:01 | Loss: 0.0029 | Acc:  0.8472
Processing |################################| (493/493) Data: 0.000096s | Batch: 0.173s | Total: 0:01:25 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8347

Epoch: 52 | LR: 0.00025000
Processing |################################| (3708/3708) Data: 0.000471s | Batch: 0.492s | Total: 0:36:07 | ETA: 0:00:01 | Loss: 0.0029 | Acc:  0.8483
Processing |################################| (493/493) Data: 0.000069s | Batch: 0.171s | Total: 0:01:24 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8412

Epoch: 53 | LR: 0.00025000
Processing |################################| (3708/3708) Data: 0.000490s | Batch: 0.485s | Total: 0:36:09 | ETA: 0:00:01 | Loss: 0.0029 | Acc:  0.8512
Processing |################################| (493/493) Data: 0.000101s | Batch: 0.166s | Total: 0:01:21 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8363

Epoch: 54 | LR: 0.00025000
Processing |################################| (3708/3708) Data: 0.000281s | Batch: 0.498s | Total: 0:36:15 | ETA: 0:00:01 | Loss: 0.0029 | Acc:  0.8495
Processing |################################| (493/493) Data: 0.000084s | Batch: 0.170s | Total: 0:01:24 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8260

Epoch: 55 | LR: 0.00025000
Processing |################################| (3708/3708) Data: 0.000371s | Batch: 0.495s | Total: 0:36:09 | ETA: 0:00:01 | Loss: 0.0029 | Acc:  0.8525
Processing |################################| (493/493) Data: 0.000071s | Batch: 0.171s | Total: 0:01:24 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8295

Epoch: 56 | LR: 0.00025000
Processing |################################| (3708/3708) Data: 0.000404s | Batch: 0.505s | Total: 0:36:08 | ETA: 0:00:01 | Loss: 0.0029 | Acc:  0.8559
Processing |################################| (493/493) Data: 0.000100s | Batch: 0.170s | Total: 0:01:23 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8428

Epoch: 57 | LR: 0.00025000
Processing |################################| (3708/3708) Data: 0.000158s | Batch: 0.495s | Total: 0:36:11 | ETA: 0:00:01 | Loss: 0.0029 | Acc:  0.8561
Processing |################################| (493/493) Data: 0.000068s | Batch: 0.165s | Total: 0:01:21 | ETA: 0:00:01 | Loss: 0.0030 | Acc:  0.8343

Epoch: 58 | LR: 0.00025000
Processing |################################| (3708/3708) Data: 0.000442s | Batch: 0.484s | Total: 0:36:12 | ETA: 0:00:01 | Loss: 0.0029 | Acc:  0.8562
Processing |################################| (493/493) Data: 0.000087s | Batch: 0.166s | Total: 0:01:21 | ETA: 0:00:01 | Loss: 0.0029 | Acc:  0.8409

Epoch: 59 | LR: 0.00025000
Processing |############################    | (3335/3708) Data: 0.001074s | Batch: 0.582s | Total: 0:32:31 | ETA: 0:03:34 | Loss: 0.0029 | Acc:  0.8564`

**Comment by dongzhuoyao** [comment]
https://github.com/bearpaw/pytorch-pose/blob/master/example/mpii.py#L96

insert:

```       
from time import sleep
sleep(2)
```

In my case, this can solve the problem, hope help someone else.
