### ISSUE TITLE
ImportError: No module named pose

### ISSUE THREAD

**Issue by wangzheallen** [bearpaw/pytorch-pose#38]
Traceback (most recent call last):
  File "example/mpii.py", line 14, in <module>
    from pose import Bar
ImportError: No module named pose

when I run the training code

**Comment by fooltball** [comment]
Having the same issue, however they do have the pose dir in this repo, probably that --recursive flag didn't check out that part

**Comment by bearpaw** [comment]
Please refer to https://github.com/bearpaw/pytorch-pose/issues/5

**Comment by wangzheallen** [comment]
Thanks!
