### ISSUE TITLE
find a bug

### ISSUE THREAD

**Issue by WuJunde** [bearpaw/pytorch-pose#39]
in _hour_glass_forward
out = up1 + up2
RuntimeError: The size of tensor a (15) must match the size of tensor b (14) at non-singleton dimension 3
because my second smallest layer of the hourglass is up1, has torch.Size([1, 512, 10, 15]), after max pool(2),it becomes [1,512,5,7], but after do up2 = self.upsample(low3), it becomes [1,512,10,14], then up1 and up2 can't be added because of the different size.

**Comment by bearpaw** [comment]
It's not a bug. You should calculate what is the resolution of the downsampled/upsampled features and design your own input resolution or network structure.
