### ISSUE TITLE
ImportError: No module named pose

### ISSUE THREAD

**Issue by zilesazoyi2** [bearpaw/pytorch-pose#5]
**# Thanks for you code! could you give me some advice?**

sun@sunwin:~$ cd /home/sun/pytorch-pose
sun@sunwin:~/pytorch-pose$ ln -s PATH_TO_MPII_IMAGES_DIR data/mpii/images
sun@sunwin:~/pytorch-pose$ CUDA_VISIBLE_DEVICES=0 python example/mpii.py -a hg4 --checkpoint checkpoint/mpii/hg4 --resume checkpoint/mpii/hg4/model_best.pth.tar -e -d
Traceback (most recent call last):
  File "example/mpii.py", line 14, in <module>
    from pose import Bar
ImportError: No module named pose
sun@sunwin:~/pytorch-pose$ CUDA_VISIBLE_DEVICES=0 python example/mpii.py -a hg4 --checkpoint checkpoint/mpii/hg4 --resume checkpoint/mpii/hg4/model_best.pth.tar -e -d
Traceback (most recent call last):
  File "example/mpii.py", line 14, in <module>
    from pose import Bar
ImportError: No module named pose
sun@sunwin:~/pytorch-pose$ CUDA_VISIBLE_DEVICES=0 python example/mpii.py -a hg1 --checkpoint checkpoint/mpii/hg1 -j 4 
Traceback (most recent call last):
  File "example/mpii.py", line 14, in <module>
    from pose import Bar
ImportError: No module named pose
sun@sunwin:~/pytorch-pose$ 
really need help! thank you !

**Comment by bearpaw** [comment]
Hi @zilesazoyi2 , try to add one line in your `~/.bashrc`

```
export PYTHONPATH=".:$PYTHONPATH"
```

And then open a new terminal, or run `source ~/.bashrc`. Then rerun the code. See if this can solve your problem.

**Comment by zilesazoyi2** [comment]
# thank you so much ! you advice really help me 
sun@sunwin:~/pytorch-pose$  CUDA_VISIBLE_DEVICES=0 python example/mpii.py -a hg4 --checkpoint checkpoint/mpii/hg4 --resume checkpoint/mpii/hg4/model_best.pth.tar -e -d
==> creating model 'hg4'
=> loading checkpoint 'checkpoint/mpii/hg4/model_best.pth.tar'
=> loaded checkpoint 'checkpoint/mpii/hg4/model_best.pth.tar' (epoch 37)
    Total params: 25.03M
    Mean: 0.4404, 0.4440, 0.4327
    Std:  0.2458, 0.2410, 0.2468

Evaluation only
/home/sun/pytorch-pose/pose/utils/imutils.py:144: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  full_img = np.zeros((img.shape[0], size * (num_cols + num_rows), 3), np.uint8)
/home/sun/pytorch-pose/pose/utils/imutils.py:160: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  full_img[row_offset:row_offset + size, col_offset:col_offset + size] = out_img
/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py:2437: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)
Processing |################################| (493/493) Batch: 2.374s | Total: 0:19:30 | ETA: 0:00:02 | Loss: 0.0010 | Acc:  0.9077
sun@sunwin:~/pytorch-pose$ 

I still confused ,you code only detect the keypoint of people? not including conection of keypoint ? just like this papers result ?
[https://arxiv.org/pdf/1603.06937.pd](url)

**thanks for you time  ,you are so  kind （∩＿∩）**

**Comment by bearpaw** [comment]
@zilesazoyi2 Hi, the paper also detect the keypoints only. The skeletons of people are just for visualization :)

**Comment by zilesazoyi2** [comment]
thanks you Ｏ（∩＿∩）Ｏ　your kindness really help me !

**Comment by Yozey** [comment]
@bearpaw Could you please explain why 

> export PYTHONPATH=".:$PYTHONPATH"
resolves the problem? Thank you. I'm a little bit confused by the python import system.

**Comment by bearpaw** [comment]
@Yozey I'm not quite familiar with python either. But I think `.` indicates the "current" directory where you run python.

**Comment by MrZhangYH** [comment]
Hi, @bearpaw 
When I run the code, it would appear: ImportError: No module named easydict.
However, after I add export PYTHONPATH=".:$PYTHONPATH" and run ~/.bashrc, it appears: ImportError: no module named 'torch'.  Could you give me some advice?
