### ISSUE TITLE
Prediction Output

### ISSUE THREAD

**Issue by chnanc001** [bearpaw/pytorch-pose#59]
what is the format of the prediction output of the .mat file? i.e. what do the numbers represent?
also, where is the code that saves this file?

any help is very much appreciated, thank you.

**Comment by bearpaw** [comment]
The code to save the mat file can be found here: https://github.com/bearpaw/pytorch-pose/blob/0867835dc33c3740774b4b4e235d6339af3b9f9e/pose/utils/misc.py#L29-L46

The predictions are generated at https://github.com/bearpaw/pytorch-pose/blob/0867835dc33c3740774b4b4e235d6339af3b9f9e/example/mpii.py#L250 

You can also visualize the results by turning on '-debug' mode.
