### ISSUE TITLE
block.expansion

### ISSUE THREAD

**Issue by sssruhan1** [bearpaw/pytorch-pose#6]
Hi,
would you mind briefly explaining what's the purpose of block.expansion in Bottleneck class? I find out it's been used several times for 

if stride != 1 or self.inplanes = planes*block.expansion:
        downsample=....

I am a little bit confused, why does this have anything to do with adding downsampling layer to self.layer 
Thank you!

**Comment by bearpaw** [comment]
Hi, sorry for the late response for that I was attending a conference these days.

`block.expansion` is a hyper parameter to define the bottleneck structures is resnet. It first appears in the original implementation of residual net: https://github.com/facebook/fb.resnet.torch/blob/master/models/resnet.lua#L71
In their implementation, this "expansion" is fixed as `4`.

**Comment by hyperfraise** [comment]
I'm pretty confused about it to. Is this more than just parametrizing the depths of all convolutions ?
