### ISSUE TITLE
Support for MPII multi person evaluation?

### ISSUE THREAD

**Issue by ahangchen** [bearpaw/pytorch-pose#60]
As illustrated in [MPII website](http://human-pose.mpi-inf.mpg.de/#evaluation), evaluation contains multi person evaluation and single person evaluation. In this project there is only single person evaluation using pckh.m. Can you support for multi person evaluation?

**Comment by bearpaw** [comment]
This repo only supports single-person pose estimation. For multi-person pose estimation, please refer to https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation
