### ISSUE TITLE
ModuleNotFoundError: No module named 'progress'

### ISSUE THREAD

**Issue by shayxurui** [bearpaw/pytorch-pose#62]
when i train the net ,there are some error,
Traceback (most recent call last):
  File "example/mpii.py", line 14, in <module>
    from pose import Bar
  File "/mnt/md0/xur/HumanPose/pytorch-pose/pose/__init__.py", line 10, in <module>
    from progress.bar import Bar as Bar

**Comment by bearpaw** [comment]
Add the following command to your bashrc:
```
export PYTHONPATH=".:$PYTHONPATH"
```

**Comment by shayxurui** [comment]
thanks for your reply,but i try this ,but still doesnot work

**Comment by bearpaw** [comment]
After saving the bashrc file, run `source ~/.bashrc`, or open a new terminal before training the network.

**Comment by bearpaw** [comment]
> Add the following command to your bashrc:
> 
> ```
> export PYTHONPATH=".:$PYTHONPATH"
> ```

**Comment by seongkyun** [comment]
Nope @bearpaw . I think that is not a correct answer. After cloning this repository, then you should copy other submodules to run this code.
Type `git submodule update --init --recursive` in copied directory on your computer.
After that, you can run this code.

`git clone some_address` cannot copy all the submodules at a once.
This is the correct answer.
