### ISSUE TITLE
LEEDS_annotations.json and ./data/lsp/mean.pth.tar

### ISSUE THREAD

**Issue by SpiritBear000** [bearpaw/pytorch-pose#63]
hi, Does anyone know how to get these two files? --LEEDS_annotations.json and ./data/lsp/mean.pth.tar
which used to test in lsp dataset

**Comment by bearpaw** [comment]
Use https://github.com/bearpaw/pytorch-pose/blob/master/miscs/gen_lsp.m to generate the `LEEDS_annotations.json`. The `mean.pth.tar` file will be generated automatically when you train on the LSP dataset for the first time.

**Comment by SpiritBear000** [comment]
ah! It’s my carelessness, thank you for your reply.
