### ISSUE TITLE
Why 8stacks network occupied GPU memory is low?

### ISSUE THREAD

**Issue by idotc** [bearpaw/pytorch-pose#66]
When I trained this network with 8 stacks, this network only occupied about 4G of GPU memory, much less than the original author's(15G). Why?

**Comment by djangogo** [comment]
batchsize

**Comment by idotc** [comment]
@djangogo The batchsize of both code is 6.

**Comment by bearpaw** [comment]
@idotc The original code is implemented with Torch.
