### ISSUE TITLE
Questions about how to test a single image

### ISSUE THREAD

**Issue by genius9527** [bearpaw/pytorch-pose#67]
Hello, I would like to ask how to use the pre-training model to visualize the test results of a single image.

**Comment by wm901115nwpu** [comment]
@genius9527 do you visualize the result of a single image?

**Comment by bearpaw** [comment]
@genius9527 @wm901115nwpu Please see https://github.com/bearpaw/pytorch-pose#testing

**Comment by wm901115nwpu** [comment]
it only test on the mpii dataset, if I test the model in the ourdataset, how todo it?

**Comment by bearpaw** [comment]
@wm901115nwpu You can simply replace the `input` https://github.com/bearpaw/pytorch-pose/blob/master/example/mpii.py#L227 by your image

**Comment by wm901115nwpu** [comment]
However, the input call the train_loader, our dataset lacks of annotations

**Comment by bearpaw** [comment]
You don't need to use the train_loader. The easiest way is to just read your image, crop/resize it to 256x256, subtract mean, and feed it to the network.

**Comment by wm901115nwpu** [comment]
meta is unknown. If I only load img, I don't get scale, center and index. How can I do?

**Comment by syusukee** [comment]
@wm901115nwpu @genius9527 Hi! Have you succeeded in visualizing your own picture ? Can you share with me about more details? Thanks a lot!!

**Comment by SamaElBaroudy** [comment]
@wm901115nwpu @genius9527 @syusukee does anyone in this thread succeeded in testing on a single image or frames of video?

**Comment by minhhoangbui** [comment]
@SamaElBaroudy Basically, you can just find the coordinates with the highest value in the heatmap. However, I couldn't use his function `get_final_preds` yet
