### ISSUE TITLE
Is there any difference with original torch implementation?

### ISSUE THREAD

**Issue by Lizw14** [bearpaw/pytorch-pose#7]
Hi, thanks for your code!

I see that the mean PCKh@0.5 of 4-stack-hourglass model trained using this code is 83.58, which is 4-5 points lower than model trained on original torch code, which is 87.8 as reported in the paper. So is there any difference between this implementation and the original code? Like the data augmentation, or the intermediate supervision?

Thank you!

**Comment by bearpaw** [comment]
@Lizw14 Hey. Thanks for your interest in this code. 

This code is a python reimplementation of the [original torch version](https://github.com/anewell/pose-hg-train). I tried my best to make the python version the same as the torch version. However, there might still be some details that are different from the original one. 

Currently, I think there might be some problems in mapping the coordinate from the 64x64 maps to the original image (I mean the full image, not the 256x256 crop). You're welcomed to contribute if you find any bugs or mistakes in this part. Thank you very much!
