### ISSUE TITLE
some question on preprocessing mpii

### ISSUE THREAD

**Issue by Ivamcoder** [bearpaw/pytorch-pose#73]
Hi @bearpaw ,
Thank you so much for your great job,
I have one question when this condition occur in dataset?  what kind of situations it cares about
https://github.com/bearpaw/pytorch-pose/blob/0f8ace7d425cfc6872a19c5ed70c8580fcdfeb08/pose/utils/transforms.py#L140

Thanks,

**Comment by Ivamcoder** [comment]
Hi @bearpaw 
how bout this line, in `new_y` , why do you use `len(img)`?
https://github.com/bearpaw/pytorch-pose/blob/0f8ace7d425cfc6872a19c5ed70c8580fcdfeb08/pose/utils/transforms.py#L166

**Comment by bearpaw** [comment]
```python
        if new_size < 2:
            return torch.zeros(res[0], res[1], img.shape[2]) \
                        if len(img.shape) > 2 else torch.zeros(res[0], res[1])
```

If the cropped region is less than 2 pixel, then it's just a one-pixel image. In this case, we just return an "blank" image with predefined resolution (e.g. 256x256).

Usually this will never happen unless there are errors in groundtruth annotations.
