### ISSUE TITLE
question in accuracy

### ISSUE THREAD

**Issue by Ivamcoder** [bearpaw/pytorch-pose#74]
Hi @bearpaw 
Thanks for all your nice comments, here you use dimension`64/10` to normalize the error , why do you use that and not using the head size? is that different from `PCK` that you have plotted in figure from log files. 
https://github.com/bearpaw/pytorch-pose/blob/b73abfa3961360321814b5af4f14fa47e0769017/pose/utils/evaluation.py#L39

**Comment by bearpaw** [comment]
This is just for training monitoring. To evaluate on original resolution, see 
https://github.com/bearpaw/pytorch-pose/blob/master/evaluation/eval_PCKh.m
or 
https://github.com/bearpaw/pytorch-pose/blob/master/evaluation/eval_PCKh.py
