### ISSUE TITLE
Environment Setup

### ISSUE THREAD

**Issue by Ivamcoder** [bearpaw/pytorch-pose#76]
Hi @bearpaw ,
I was confused in some issues it is reported they got results with Pytorch 0.2.0  and some with 0.4.0
for example I got for `torch 0.4.1 cuda 90 python3.7` the following error

`File "example/main.py", line 260
    target = target.cuda(async=True)
                             ^
SyntaxError: invalid syntax
c
`
What is final set up for running the training? `Pytorch ?  cuda:? Python:?`

**Comment by bearpaw** [comment]
Fixed see https://github.com/bearpaw/pytorch-pose/commit/916798e450187febcc72c55b8ddf1c397b863243

**Comment by Ivamcoder** [comment]
I have setup with `cuda:8`, `pytorch1.0.0` ,and `python2.7` for training, and seems work without the change you have made in ` target = target.cuda(async=True)`.

**Comment by bearpaw** [comment]
I don't know the reason, but we don't need this line because we do it here: https://github.com/bearpaw/pytorch-pose/blob/master/example/main.py#L261
