### ISSUE TITLE
 TypeError: 'numpy.float64' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by minghuatang** [bearpaw/pytorch-pose#8]
Hi! I ran the testing command and I got this error:

`Traceback (most recent call last):
  File "example/mpii.py", line 309, in <module>
    main(parser.parse_args())
  File "example/mpii.py", line 88, in main
    loss, acc, predictions = validate(val_loader, model, criterion, args.debug, args.flip)
  File "example/mpii.py", line 238, in validate
    gt_batch_img = batch_with_heatmap(inputs, target)
  File "/home/minghua/Codes/intel-contest/pytorch-pose/pose/utils/imutils.py", line 169, in batch_with_heatmap
    sample_with_heatmap(inp.clamp(0, 1), outputs[n], num_rows=num_rows, parts_to_show=parts_to_show)
  File "/home/minghua/Codes/intel-contest/pytorch-pose/pose/utils/imutils.py", line 144, in sample_with_heatmap
    full_img = np.zeros((img.shape[0], size * (num_cols + num_rows), 3), np.uint8)
TypeError: 'numpy.float64' object cannot be interpreted as an index`

Thank you!

**Comment by bloodymeli** [comment]
same here...

**Comment by bearpaw** [comment]
Hi, I cannot repeat this error in my environment. Could you please provide more details about your running environment? Thank you very much!

**Comment by bloodymeli** [comment]
Hi, I found a quick way to fix this:
Change line 141 in imutils.py to
num_cols = int(np.ceil(float(len(parts_to_show)) / num_rows))
instead of
num_cols = np.ceil(float(len(parts_to_show)) / num_rows)

the output of np.ceil is apparently a float (at least in my version).

**Comment by bearpaw** [comment]
@bloodymeli Thanks. The bug has been fixed.
