### ISSUE TITLE
detections_our_format

### ISSUE THREAD

**Issue by Ivamcoder** [bearpaw/pytorch-pose#82]
Hi @bearpaw 

which script `'evaluation/data/detections_our_format.mat'` produce this result? and `jnt_missing` attribute is the same as the attribute `` in `data loader` during training, I could not find that, I mean the only  joints which has zero coordinates in their annotation are considered as missed ones ? not occluded ones?

**Comment by Ivamcoder** [comment]
Why do you have  `SC_BIAS` in addition to '0.5 threshold'? `SC_BIAS` is considered for previous `State of arts`?

**Comment by bearpaw** [comment]
1. `detections_our_format.mat` is from http://www.cims.nyu.edu/~tompson/data/mpii_valid_pred.zip (see Readme)
2. Eval code is from MPII's official evaluation toolkit: http://human-pose.mpi-inf.mpg.de/results/mpii_human_pose/evalMPII.zip
