### ISSUE TITLE
train acc is low

### ISSUE THREAD

**Issue by syusukee** [bearpaw/pytorch-pose#83]
![acc](https://user-images.githubusercontent.com/28001951/53459574-5600fa00-3a75-11e9-818a-72c704301691.png)
hello, this is a really great work ! But I have a question about the train accuracy, why my train acc is always lower than the val acc ? hope you can help me @bearpaw

**Comment by bearpaw** [comment]
Your result seems good. See my log file here: https://drive.google.com/drive/folders/0B63t5HSgY4SQLTBVakJVeDBrNms

**Comment by syusukee** [comment]
sorry, I've pasted the wrong log. Above is the one I downloaded from your log file in the condition of stack=2, block=1. And I found that, when epoch nearly 100, your train acc is higher than the val acc :
![1](https://user-images.githubusercontent.com/28001951/53461302-189f6b00-3a7b-11e9-806e-385c7fb1f113.png)
But in my own log file , the train acc is always much lower than the val acc:
![11](https://user-images.githubusercontent.com/28001951/53461387-5b614300-3a7b-11e9-9a64-2322d9c3eaf2.png)
and this problem is more obvious in stack=8,block=1:
![111](https://user-images.githubusercontent.com/28001951/53461527-d0347d00-3a7b-11e9-824a-685314544ad8.png)
look forward to your reply!

**Comment by syusukee** [comment]
I have set up epoch=100, is this related to my set up?

**Comment by bearpaw** [comment]
Probably it's OK since I've changed the code a lot since the initial release. Can you run `evaluation/eval_PCKh.py` to see the PCKh score?

**Comment by syusukee** [comment]
I've draw a table like you offered, and the result is as follows:
![_20190228101325](https://user-images.githubusercontent.com/28001951/53536512-b2c9e680-3b41-11e9-9efb-3968cd2663d0.png)
Compared with your result, I think it's a satisfying one. Thank you so much for your help!!

**Comment by bearpaw** [comment]
Awesome! I am closing this issue.
