### ISSUE TITLE
The test results are too bad！

### ISSUE THREAD

**Issue by 904281665** [bearpaw/pytorch-pose#91]
Hello, thank you very much for the convenience brought by your work.
I tried to implement a test.py file. My input image is the pedestrian after being detected. So I set the center to the image center. Set the **h** variable in your get_transform() method to the height of my input image. Then make predictions and find that the effect is very poor. Is it that I am doing this incorrectly? I hope to get your help. Thank you very much.

**Comment by xtyDoge** [comment]
@904281665 Hi! Would u like to show your test file here? I try to test this model on just an image but cannot find a test file here. THX!
